# Catppuccin colorscheme

# ASTRIDS CONFIGURATION with my catppuccin colorscheme.

format = """
[](red)\
$os\
$username\
$directory\
$git_branch\
$git_status\
[](fg:yellow bg:green)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:green bg:blue)\
$docker_context\
[](fg:blue bg:mauve)\
$time\
$cmd_duration\
$character
"""

# Disable the blank line at the start of the prompt
# add_newline = false

palette = "catppuccin_mocha"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"


# replace the last symbol color based on erorr or success
# [ ](fg:mauve)\ # replaced with success or error character
[character]
success_symbol =  "[ ](fg:mauve)"
error_symbol =    "[ ](fg:red)"
disabled = false


# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:red fg:crust"
style_root = "bg:red"
format = '[$user ]($style)[](bg:peach fg:red)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:red fg:crust"
disabled = true # Disabled by default

[directory]
style = "bg:peach fg:crust"
format = "[ $path ]($style)[](fg:peach bg:yellow)"
repo_root_style = "bg:black fg:white"
repo_root_format = "[ $repo_root$path]($style)[](fg:peach bg:yellow)"
truncation_length = 2
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Library/CloudStorage/OneDrive-Personal" = "☁️ "
"Library/CloudStorage/OneDrive-Personal/Raj_school_work/UNIVERSITY/Year2" = "☁️ /Uni/Year2"

# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[c]
symbol = " "
style = "bg:green fg:crust"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:blue fg:crust"
format = '[ $symbol $context ]($style)'

[elixir]
symbol = " "
style = "bg:green fg:crust"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:green fg:crust"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:yellow fg:crust"
format = '[ $symbol $branch ]($style)'
ignore_branches = ["master", "main"]

[git_status]
style = "bg:yellow fg:crust"
format = '[ $all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:green fg:crust"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:green fg:crust"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:green fg:crust"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:green fg:crust"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:green fg:crust"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:green fg:crust"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:green fg:crust"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:green fg:crust"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:green fg:crust"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = true
time_format = "%R" # Hour:Minute Format
style = "bg:mauve fg:crust"
format = '[ ♥ $time ]($style)[](fg:mauve bg:green)'

[cmd_duration]
style = "bg:mauve fg:crust"
min_time = 500
format = '[ $duration]($style)'
