"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[mgr]
linemode      = "mtime"

show_hidden   = false
title_format   = "Yazi: {cwd}"



[plugin]
prepend_preloaders = [
    # Replace magick, image, video with mediainfo
    { mime = "{audio,video,image}/*", run = "mediainfo" },
    { mime = "application/subrip", run = "mediainfo" },
]
prepend_previewers = [
    # Replace magick, image, video with mediainfo
    { mime = "{audio,video,image}/*", run = "mediainfo"},
    { mime = "application/subrip", run = "mediainfo" },

    # Plugin
    { name = "*.csv", run = 'piper -- bat -p --color=always "$1"' },
    { name = "*.md", run = 'piper -- CLICOLOR_FORCE=1 glow -w=$w -s=dark' },
    { name = "*/",run  = 'piper -- eza -TL=3 --color=always --icons=always --group-directories-first --no-quotes "$1"'},
]

  append_previewers = [
    { name = "*", run  = 'piper -- hexyl --border=none --terminal-width=$w "$1"'},
]



[preview]

[opener]
edit = [
    { run = 'nvim "$@"', desc = "NeoVim", block = true, for = "unix" },
    { run = 'code "$@"', desc = "VSCode", block = true, for = "unix" },
]
open = [
	{ run = 'open "$@"', desc = "Open", orphan = true, for = "macos" },
]


[open]
prepend_rules = [
#     # Folder
#     { name = "*/", use = ["edit", "open", "reveal"] },
#     # Text
#     { mime = "text/*", use = ["edit", "reveal"] },
#     # Image
#     { mime = "image/*", use = ["open", "reveal"] },
#     # Media
#     { mime = "{audio,video}/*", use = ["play", "reveal"] },
#     # Archive
#     { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", use = ["extract", "reveal"] },
#     # JSON
#     { mime = "application/{json,ndjson}", use = ["edit", "reveal"] },
#     { mime = "*/javascript", use = ["edit", "reveal"] },
#     # Empty file
#     { mime = "inode/empty", use = ["edit", "reveal"] },
#     # Fallback
    { name = "*/", use = ["reveal", "edit"] },
    { name = "*", use = ["edit", "open", "reveal"] },
]


[tasks]
[input]
[confirm]
[pick]
[which]
